### ISSUE TITLE
Duplicating attachments by right-clicking on attachment and selecting "duplicate attachment".

### ISSUE THREAD

**Issue by bjohas** [retorquere/zotero-edtechhub#10]
https://github.com/zotero/zotero/issues/1626

A string would need to be added to the duplicate: "-copy-"+date", e.g. "-copy-20190721" before the ".pdf" (or whatever type the attachment is) to indicate that it's a newer version. I.e. 

somestring.pdf

if copied today would change to

somestring-copy-20190721.pdf

I don't know whether the plugin has got access to the user name? In that case it would be even better if the string was "-copy-"+user+date, i.e.

somestring-copy-bjohas-20190721.pdf

**Comment by retorquere** [comment]
It does have access to the username, but I thought you wanted this as a change on zotfile?

**Comment by bjohas** [comment]
No - it's not related to ZotFile. I'll add to the project kanban regarding the zotfile change (whcih I think is no longer needed, as I'll explain)

**Comment by bjohas** [comment]
I have a slightly amended request.

somestring.pdf

should change to

somestring-bjohas-20190721-{ID}.pdf

where {ID} is the first part of archiveLocation. I.e. if archiveLocation is A;B;C;D, then {ID}=sanitised(A), where 'sanitised' replaces '/' and ':' (and other characters that should not be in filenames) with '_'. So e.g. if 

archiveLocation = 10/d254jm;2339240:NDCLGGGP

then the file becomes 

somestring-bjohas-20190721-10_d254jm.pdf

If archiveLocation is empty, then could there let's just use 

somestring-bjohas-20190721-__NO_AL__.pdf

(If it's easy to do a popup, then there could be a warning too, but that's really not necessary if it counts as UI.)

(I've also omitted 'copy' as it's pretty clear that we're dealing with a copy)

**Comment by bjohas** [comment]
Rationale: This creates a copy, that can be used as a copy, but also bakes in the archiveLocation. THis means the PDF can now be used outside Zotero (e.g. in analysis software) without losing the reference to Zotero.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 0.0.13.46](https://github.com/retorquere/zotero-edtechhub/releases/download/builds/zotero-edtechhub-0.0.13.46.xpi) ("fixes #10")

Install in Zotero by downloading [test build 0.0.13.46](https://github.com/retorquere/zotero-edtechhub/releases/download/builds/zotero-edtechhub-0.0.13.46.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
this currently only works for linked and imported files. Snapshots (imported URLs) are considerably more work and don't fit the use-case anyhow it seems to me.

**Comment by bjohas** [comment]
Totally fine - our use-case is just to duplicate imported files. Linked files are great too. Snapshots not necessary.

**Comment by bjohas** [comment]
Have tested - works well! 

10/d254jm  becomes 10d254jm but should become 10_d254jm.

**Comment by retorquere** [comment]
Should I remove linked?

**Comment by bjohas** [comment]
You mean remove linked files? No, I can see that being useful to people. So if it's working, then leave it in!

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 0.0.13.47](https://github.com/retorquere/zotero-edtechhub/releases/download/builds/zotero-edtechhub-0.0.13.47.xpi) ("fixes #10")

Install in Zotero by downloading [test build 0.0.13.47](https://github.com/retorquere/zotero-edtechhub/releases/download/builds/zotero-edtechhub-0.0.13.47.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
> 10/d254jm becomes 10d254jm but should become 10_d254jm.

This should be fixed in .47

**Comment by bjohas** [comment]
Many thanks! I cannot see the option to duplicate the attachment any more. Why might that be?

**Comment by bjohas** [comment]
Hold on - it seems to work on some files, but not all... Hmm...

**Comment by retorquere** [comment]
How large is this library?

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 0.0.13.48](https://github.com/retorquere/zotero-edtechhub/releases/download/builds/zotero-edtechhub-0.0.13.48.xpi) ("logging for file dup")

Install in Zotero by downloading [test build 0.0.13.48](https://github.com/retorquere/zotero-edtechhub/releases/download/builds/zotero-edtechhub-0.0.13.48.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Can you 

* Install .48
* Go into `Help` - `Debug Output Logging` - `Restart with Logging Enabled...`
* Let Zotero restart
* Replicate the problem
* Go into `Help` - `Send EdTech hub debug log`
* Post the ID you get in the popup that follows

**Comment by bjohas** [comment]
OK, let do that!

**Comment by bjohas** [comment]
[Debug Output dup.txt](https://github.com/retorquere/zotero-edtechhub/files/3465331/Debug.Output.dup.txt)

**Comment by bjohas** [comment]
In this output, the first right click was not successful Ii.e. didn't give the option to duplicate). The 2nd right click (on another item) was successfu. (i.e. it did give the option to duplicate). As far as I can tell, both items are 'similar' - same type, one PDF attachment (not  a link)...

**Comment by retorquere** [comment]
Of the first, it says it's an imported URL (which I though was a website snapshot), which is why it's not enabled.

You don't have to manually attach the logfile BTW. Step 5/6 will give me the logfile automatically.

**Comment by bjohas** [comment]
They are both PDFs - they come up with the PDF logo, and I've check the file system location too.

**Comment by retorquere** [comment]
If you select `Show file` from the popup menu for the first one, do you see a single PDF?

**Comment by bjohas** [comment]
Yes ... and if I copy the PDF e.g. to Downloads, and re-import, a new item is created. On that item, the 'duplicate' function works.

**Comment by retorquere** [comment]
I'm not surprised by that. I'm surprised the original shows as imported URL. I'll ask on zotero-dev.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 0.0.13.50](https://github.com/retorquere/zotero-edtechhub/releases/download/builds/zotero-edtechhub-0.0.13.50.xpi) ("import URL can also be PDF")

Install in Zotero by downloading [test build 0.0.13.50](https://github.com/retorquere/zotero-edtechhub/releases/download/builds/zotero-edtechhub-0.0.13.50.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by bjohas** [comment]
Thank you! This works now also on the items that didn't work before.

Does that mean this issue is done, or do we need to wait for zotero-dev? 

Would it be worth releasing 0.0.14 ?

**Comment by retorquere** [comment]
Done. I already got confirmation from zotero-dev.

**Comment by bjohas** [comment]
Thanks!
