### ISSUE TITLE
Assign EdTech Hub ID should work on all item types 

### ISSUE THREAD

**Issue by bjohas** [retorquere/zotero-edtechhub#11]
Where the item type has "archiveLocation", the id should be go there. Where the item type doesn't have archiveLocation, it should be put into extra as "archiveLocation:.....".

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 0.0.8.27](https://github.com/retorquere/zotero-edtechhub/releases/download/builds/zotero-edtechhub-0.0.8.27.xpi) ("fixes #11")

Install in Zotero by downloading [test build 0.0.8.27](https://github.com/retorquere/zotero-edtechhub/releases/download/builds/zotero-edtechhub-0.0.8.27.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by bjohas** [comment]
This build doesn't seem to work for me. The right-click action is renamed (as per https://github.com/retorquere/zotero-edtechhub/issues/12) but doesn't seem to work on any item type.

**Comment by retorquere** [comment]
What itemtype are you trying this on? It seems to work for me.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 0.0.8.28](https://github.com/retorquere/zotero-edtechhub/releases/download/builds/zotero-edtechhub-0.0.8.28.xpi) ("fixes #11")

Install in Zotero by downloading [test build 0.0.8.28](https://github.com/retorquere/zotero-edtechhub/releases/download/builds/zotero-edtechhub-0.0.8.28.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
0.0.8.28 adds some logging, can you try that? Please first enable debug logging from the help menu, then reproduce the problem, then go back into the help menu, view the debug log, copy its contents to a text file and attach it here.

**Comment by bjohas** [comment]
(3)(+0000000): {EdTech hub error}: assignKey TypeError: this.fieldID is undefined

**Comment by bjohas** [comment]
I assume that's the one - I can send the text file, but the other bits don't look relevant. Btw. I'm on Ubuntu if it makes a difference.

**Comment by bjohas** [comment]
Actually, it looks like I get that error on all item types.

**Comment by retorquere** [comment]
I'll need the full contents of the log

**Comment by bjohas** [comment]
[JavaScript Error: "Item field data not yet loaded"]

[JavaScript Error: "The connection to wss://stream.zotero.org/ has terminated unexpectedly. Some data may have been transferred."]

[JavaScript Error: "WebSocket connection closed: 1006 "]

version => 5.0.72, platform => Linux x86_64, oscpu => Linux x86_64, locale => en-GB, appName => Zotero, appVersion => 5.0.72, extensions => Zotero LibreOffice Integration (5.0.20.SA.5.0.72, extension), Zotero DOI Manager (1.3.8, extension), EdTechHub for Zotero (0.0.8.28, extension)

(4)(+0030906): SELECT IA.itemID FROM itemAttachments IA NATURAL JOIN items I LEFT JOIN itemData ID ON (IA.itemID=ID.itemID AND fieldID=1) LEFT JOIN itemDataValues IDV ON (ID.valueID=IDV.valueID) WHERE parentItemID=? AND linkMode NOT IN (?) AND IA.itemID NOT IN (SELECT itemID FROM deletedItems) ORDER BY contentType='application/pdf' DESC, value=? DESC, dateAdded ASC [312, 3, 'https://cam.ldls.org.uk/vdc_100063353925.0x000001']

(4)(+0000010): SELECT IA.itemID FROM itemAttachments IA NATURAL JOIN items I LEFT JOIN itemData ID ON (IA.itemID=ID.itemID AND fieldID=1) LEFT JOIN itemDataValues IDV ON (ID.valueID=IDV.valueID) WHERE parentItemID=? AND linkMode NOT IN (?) AND IA.itemID NOT IN (SELECT itemID FROM deletedItems) ORDER BY contentType='application/pdf' DESC, value=? DESC, dateAdded ASC [312, 3, 'https://cam.ldls.org.uk/vdc_100063353925.0x000001']

(4)(+0000006): SELECT IA.itemID FROM itemAttachments IA NATURAL JOIN items I LEFT JOIN itemData ID ON (IA.itemID=ID.itemID AND fieldID=1) LEFT JOIN itemDataValues IDV ON (ID.valueID=IDV.valueID) WHERE parentItemID=? AND linkMode NOT IN (?) AND IA.itemID NOT IN (SELECT itemID FROM deletedItems) ORDER BY contentType='application/pdf' DESC, value=? DESC, dateAdded ASC [312, 3, 'https://cam.ldls.org.uk/vdc_100063353925.0x000001']

(4)(+0000002): SELECT IA.itemID FROM itemAttachments IA NATURAL JOIN items I LEFT JOIN itemData ID ON (IA.itemID=ID.itemID AND fieldID=1) LEFT JOIN itemDataValues IDV ON (ID.valueID=IDV.valueID) WHERE parentItemID=? AND linkMode NOT IN (?) AND IA.itemID NOT IN (SELECT itemID FROM deletedItems) ORDER BY contentType='application/pdf' DESC, value=? DESC, dateAdded ASC [312, 3, 'https://cam.ldls.org.uk/vdc_100063353925.0x000001']

(4)(+0000004): SELECT IA.itemID FROM itemAttachments IA NATURAL JOIN items I LEFT JOIN itemData ID ON (IA.itemID=ID.itemID AND fieldID=1) LEFT JOIN itemDataValues IDV ON (ID.valueID=IDV.valueID) WHERE parentItemID=? AND linkMode NOT IN (?) AND IA.itemID NOT IN (SELECT itemID FROM deletedItems) ORDER BY contentType='application/pdf' DESC, value=? DESC, dateAdded ASC [312, 3, 'https://cam.ldls.org.uk/vdc_100063353925.0x000001']

(3)(+0003988): {EdTech hub}: assignKey: {"item":312}

(3)(+0000000): {EdTech hub error}: assignKey TypeError: this.fieldID is undefined

**Comment by retorquere** [comment]
Ah I see. I'll have a new version available shortly, but next time, please attach rather than paste, it's easier to keep the overview.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 0.0.8.29](https://github.com/retorquere/zotero-edtechhub/releases/download/builds/zotero-edtechhub-0.0.8.29.xpi) ("enforce wait for Zotero startup")

Install in Zotero by downloading [test build 0.0.8.29](https://github.com/retorquere/zotero-edtechhub/releases/download/builds/zotero-edtechhub-0.0.8.29.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Right -- Zotero plugins must wait until Zotero gives the go-ahead before they are allowed to do pretty much anything, and this go-ahead can take several seconds after Zotero itself seems up and running. There's absolutely nothing I can (safely) do about this -- trust me, I've tried for my other plugins.

0.0.8.29 will keep a warning open while the plugin is waiting for the go-ahead and will also defer any key-assign until the go-ahead has come. I hadn't noticed because I'm so used to waiting it out, and BBT (one of my other plugins) also shows this popup warning.

**Comment by bjohas** [comment]
The warning is really useful - I think I've hit that issue with other functionality, so it's really helpful to have the warning.

The plugin now works again, but still only e.g. on journal articles.

I've attached a RIS file and another log. The RIS is of a thesis, and the action should assign LibraryID:itemKey as archiveLocation, but that doesn't work.

[Zotero_log.txt](https://github.com/retorquere/zotero-edtechhub/files/3437972/Zotero_log.txt)
[Zotero_thesis.ris.txt](https://github.com/retorquere/zotero-edtechhub/files/3437973/Zotero_thesis.ris.txt)

**Comment by retorquere** [comment]
Well yeah -- as per https://github.com/retorquere/zotero-edtechhub/issues/5#issuecomment-514201813 and later:

* this item does not have a short DOI either in the `DOI` field (which this item doesn't have) or the `extra` field
* it is not tagged with `no doi found`

so the plugin does nothing. If you add `shortDOI: 10/bc799g` (or somesuch) to the `extra` field, it will generate the archiveLocation key.

**Comment by bjohas** [comment]
Ahh - yes. My bad. The issue is the short-doi quite rightly only looks for a DOI for types that should have DOIs. So e.g. a thesis is never assigned no-doi-found. I'll open a new issue.
