### ISSUE TITLE
Always add libraryID:itemKey to archiveLocation

### ISSUE THREAD

**Issue by bjohas** [retorquere/zotero-edtechhub#13]
I think it would be good if the string "libraryID:itemKey" was always added to archiveLocation. (unless it's already there) Then, if there's a DOI, this is just pre-pended with a ";" 

`shortdoi;libraryID:itemKey`

but otherwise it just stays at

`libraryID:itemKey`

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 0.0.9.33](https://github.com/retorquere/zotero-edtechhub/releases/download/builds/zotero-edtechhub-0.0.9.33.xpi) ("fixes #13")

Install in Zotero by downloading [test build 0.0.9.33](https://github.com/retorquere/zotero-edtechhub/releases/download/builds/zotero-edtechhub-0.0.9.33.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
BTW the releases that show up at https://github.com/retorquere/zotero-edtechhub/releases can be installed by users and will automatically upgrade. I merge there whenever I close issues.

**Comment by bjohas** [comment]
Perfect - thank you! This issue can be closed!

Great to know about the releases as well! We've started to use the plugin in our working group, and it's great to know that it will just auto-update!

**Comment by retorquere** [comment]
That's why we have #9 - you'll inherit all these trappings if it's set up properly.

**Comment by bjohas** [comment]
Brilliant, thank you. I'll get round to it asap!

**Comment by retorquere** [comment]
No rush on my part. Make note of how you do it, because when it's in place, you'll need to destroy it so we can transfer this repo including issues. You'll need to reapply the config after transfer.
