### ISSUE TITLE
When merging items, 'stack' the archiveLocation

### ISSUE THREAD

**Issue by bjohas** [retorquere/zotero-edtechhub#14]
When items are merged, it is possible to combine the archiveLocation of the two merged items for the archiveLocation of the new item?

`merged_item.archiveLocation = itemA.archiveLocation + ";" + itemB.archiveLocation`

where ideally itemA would be the item selected as 'primary' during the merge process.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 0.0.10.36](https://github.com/retorquere/zotero-edtechhub/releases/download/builds/zotero-edtechhub-0.0.10.36.xpi) ("fixes #14")

Install in Zotero by downloading [test build 0.0.10.36](https://github.com/retorquere/zotero-edtechhub/releases/download/builds/zotero-edtechhub-0.0.10.36.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by bjohas** [comment]
Sorry, this doesn't work for me.  I get

`merged_item.archiveLocation = itemA.archiveLocation`

where itemA is the item selected as 'primary' during the merge process.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 0.0.12.42](https://github.com/retorquere/zotero-edtechhub/releases/download/builds/zotero-edtechhub-0.0.12.42.xpi) ("use full namespace")

Install in Zotero by downloading [test build 0.0.12.42](https://github.com/retorquere/zotero-edtechhub/releases/download/builds/zotero-edtechhub-0.0.12.42.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by bjohas** [comment]
Perfect - thank you, that works!

**Comment by bjohas** [comment]
This issue can be closed!
