### ISSUE TITLE
Item-type 14 (item with no parent item) causes plugin to 'crash'

### ISSUE THREAD

**Issue by bjohas** [retorquere/zotero-edtechhub#15]
When there's an item that doesn't have a parent item, the log says

`(3)(+0000004): {EdTech hub error}: assignKey Error: 'extra' is not a valid field for type 14`

and then does not progress to other items. I am unsure which item types correspond to items with parent items and items without parent items. However, items that do not have parent items should be skipped.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 0.0.10.37](https://github.com/retorquere/zotero-edtechhub/releases/download/builds/zotero-edtechhub-0.0.10.37.xpi) ("fixes #15")

Install in Zotero by downloading [test build 0.0.10.37](https://github.com/retorquere/zotero-edtechhub/releases/download/builds/zotero-edtechhub-0.0.10.37.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by bjohas** [comment]
Thank you - this works!
