### ISSUE TITLE
Record the group id / item id (Tag: merge)

### ISSUE THREAD

**Issue by bjohas** [retorquere/zotero-edtechhub#2]
Would be good to include the Zotero group id / Zotero item id in the child note as well (which means that item ids disappearing through the search still be searched for) (Old item ids are kept in the DB afaik, but they can no longer be searched through the UI.)

**Comment by retorquere** [comment]
Can you search on itemID? How would the user know the itemID?

**Comment by bjohas** [comment]
The item id is communicated in zotero://-style links. Those stop working if the itemID changes (obviously), so a fall-back would be for the user to search for the itemID in a 'search everything'. 

We're also using itemIDs in our scannable cite. 

Btw. you can also search for the itemID in search search box, but this will not find old ids.

**Comment by retorquere** [comment]
Would it matter whether the itemID is kept with the attendant RIS? This would be slower.

**Comment by bjohas** [comment]
Not entirely sure what that means.

**Approach 1**

For example, as in the request here: https://github.com/edtechhub/zotero-edtechhub/issues/1, a child note could be:

```
Merged record
Today's date, Zotero user

RIS itemID[item1]
TY  - BOOK 
TI  - ABC 

RIS itemID[item2]
TY  - BOOK 
TI  - ABC 
```

**Approach 2**

However, if it is better to just put the merged IDs into another Zotero field, then that would be fine too! E.g.

```
Merged record
Today's date, Zotero user

TY  - BOOK 
TI  - ABC 
...

TY  - BOOK 
TI  - ABC 
...
```

and then then 'Extra' has "oldID:XYZ" appended.

Both ways would be fine!

**Comment by retorquere** [comment]
I'm saying the first sample would be slower, as I'd have to export them one-by-one rather than all at once to be sure which itemID belongs with which RIS section. If I can just add a number of `oldID:` lines at the bottom, that would be faster.

**Comment by bjohas** [comment]
OK, great! Let's add the itemID for both items at the bottom of the note.

**Comment by retorquere** [comment]
I've just requested travis access for this repo but it needs owner approval. Can I be added as an owner while we work on this? And can you approve travis in the interim?

**Comment by bjohas** [comment]
Done!

**Comment by retorquere** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 0.0.3.5](https://github.com/edtechhub/zotero-edtechhub/releases/download/builds/zotero-edtechhub-0.0.3.5.xpi) ("ping travis")

Install in Zotero by downloading [test build 0.0.3.5](https://github.com/edtechhub/zotero-edtechhub/releases/download/builds/zotero-edtechhub-0.0.3.5.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
If you install 0.0.3.5 you can see if it does what you want

**Comment by bjohas** [comment]
Great - that looks good!

(1) I was expecting the item group (e.g. 2339240) and the ItemKey (something like 37Q23EK3). Instead I got  "oldItem: 175460", which I cannot place as an id. What is it?

(2) could the note start with 
**Item history (date)**

Looks very good though!!

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 0.0.3.7](https://github.com/retorquere/zotero-edtechhub/releases/download/builds/zotero-edtechhub-0.0.3.7.xpi) ("add date, keys instead of item IDs")

Install in Zotero by downloading [test build 0.0.3.7](https://github.com/retorquere/zotero-edtechhub/releases/download/builds/zotero-edtechhub-0.0.3.7.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
`175460` is the itemID (which is what you initially asked for and which is always numeric), things like `37Q23EK3` are itemKeys. 

Try 0.0.3.7.

**Comment by retorquere** [comment]
Not sure yet I can get the Zotero user, looking for that

**Comment by bjohas** [comment]
Great!

For me, the group comes out as 25. Have I asked for the wrong thing again? I mean the group that occurs here:
https://www.zotero.org/groups/2339240/items/VXRS54KL

Nice touch with the table at the end :) Thanks!

**Comment by bjohas** [comment]
TBH, the zotero user is not so important - happy to leave that be, and close this issue :)

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 0.0.3.8](https://github.com/retorquere/zotero-edtechhub/releases/download/builds/zotero-edtechhub-0.0.3.8.xpi) ("add user")

Install in Zotero by downloading [test build 0.0.3.8](https://github.com/retorquere/zotero-edtechhub/releases/download/builds/zotero-edtechhub-0.0.3.8.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
I'll look at the group ID

**Comment by bjohas** [comment]
User name - nice!

Just looked it up in a translator I had: What we want is item.libraryID

**Comment by retorquere** [comment]
That's what I'm putting there.

**Comment by retorquere** [comment]
(translators sometimes get stuff named differently than Zotero internals)

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 0.0.3.9](https://github.com/retorquere/zotero-edtechhub/releases/download/builds/zotero-edtechhub-0.0.3.9.xpi) ("libraryPath instead of libraryID")

Install in Zotero by downloading [test build 0.0.3.9](https://github.com/retorquere/zotero-edtechhub/releases/download/builds/zotero-edtechhub-0.0.3.9.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
BTW this is why I needed Travis. I have a [tool to quickly scaffold new Zotero plugins](https://www.npmjs.com/package/generator-zotero-plugin), and the scaffold comes with tools for formal releases but also issue-bound releases such as posted here by @blip-bloop. Way to hard ti reason about code if you can't quickly get builds into the hands of users to see if you git it right. The toolchain requires Travis.

**Comment by bjohas** [comment]
Travis is really cool - not used it before, but getting builds into the hands of users is just the right approach - thank you.

All works as expected now.

One caveat, but that's minor, and a matter of opinion: When you merge, the child notes are written into the RIS. That could get a bit ugly. However, in our scenario (where it's about tracking items in a literature review) the notes might contain item specific data, and it's then important to know which note belonged to which item. So this should stay as it is.

I would call this 'issue' resolved! Thank you so much!

**Comment by retorquere** [comment]
I also have things set up so only I can close issues -- I need the reminder that I must merge to master.
