### ISSUE TITLE
Also preserve data when changing record

### ISSUE THREAD

**Issue by bjohas** [retorquere/zotero-edtechhub#3]
Could data also be preserved when changing Zotero item type? I.e. record the old item in a note when changing type? Then we don't have to worry about disappearing fields.

**Rationale for 'type change'.** 

When I change the type of a Zotero record, I don't know which fields are supported in the new type. So I often change, then notice that a piece of info will be deleted. I press cancel, copy that piece (or pieces) if needed, then change type, then copy it back into the item or a note. This process would be better if the whole record was simply recorded in a note. I can then copy the new data into the record as needed.

The item would only need to record the data in a note if metadata disappears. However, type changes are rare enough (in our work) that it's totally ok if the plugin records the change in a child note.

**Comment by retorquere** [comment]
Plugins don't get pre-change notifications -- most of the things you want (such as merge tracking) are going to need a method known as runtime-patching, or "monkey-patching". So this is possible, but fragile.

This way of extending Zotero is inherently fragile -- I'd be modifying behavior of Zotero that the Zotero devs have not planned on being changed that way.

The Zotero internals have been pretty stable, and my own plugins do this extensively, but I just wanted you to have this heads-up.

The plugin could require upkeep in the future if Zotero does change, which almost certainly will be the case when the Electron port comes.

The Zotero devs have indicated that they intend to keep the internals the same across the port where possible (if even only for their own sake) but cannot make guarantees here.

**Comment by bjohas** [comment]
Thanks!

So this would be possible, but only as "always copy metadata to note when the type changes". That would be fine.

Did I understand correctly?

**Comment by retorquere** [comment]
I think it should be possible (I have not investigated) but if it is, it will be as a runtime patch that intercepts saves, not using the formally supported notification infrastructure of Zotero, because that only gets notified after the change is already applied. And such runtime patches are in principle fragile. 

It is not at all uncommon for the Zotero devs to request my own plugins be disabled when they get support requests, because they employ these runtime patches. I'm just giving a heads-up: possible, but not in a way that Zotero formally supports.

**Comment by bjohas** [comment]
If it's tricky, then let's not do it.

Here's an alternative approach: In the same way as we're copying data to a note (on merge), could add a user interaction to save data to a note arbitrarily? Then, if I change the record, I can just dump the data to a note in advance. That would be sufficient for our purposes.

What do you think?

**Comment by retorquere** [comment]
The merge uses runtime patching :smile:

The user interaction is possible. Intercepting saves is a little trickier than merges because they could be part of a transaction, merges are not.

**Comment by bjohas** [comment]
Aha :) I had thought that might be the case :)

Well, I think dumping data to a note could be useful for other things as well, so how about just dumping data to a note (i.e. prompted by user interaction).

**Comment by bjohas** [comment]
Actually, this one has a work-around:

- You try to chamge type, and notice you will lose data
- if you want a record, then cancel
- duplicate
- merge -> You now have a note with the item data
- now change type and restore what you need.

That's sufficient for our purposes, so we can call this one done as well!
