### ISSUE TITLE
Assigning items a unique id

### ISSUE THREAD

**Issue by bjohas** [retorquere/zotero-edtechhub#5]
Problem: We would like to be able to refer to Zotero items uniquely, from documents/databases outside Zotero. We require a plain text code to refer to Zotero items.

Proposal: Use a process whereby (if avaialble) the shortDOI is used (c.f. https://github.com/bwiernik/zotero-shortdoi/releases/latest), otherwise the internal Zotero itemID is used.

```
if (item has DOI) {
  itemRef = getShortDOI(item.DOI);
} else {
  itemRef = item.group + ":" + item.key
}
item.locInArchive.replace(itemRef,"");
item.locInArchive = itemRef + ";" + item.locInArchive;
item.locInArchive.replace(";;+",";"); 
```

**Comment by retorquere** [comment]
Assign in what sense?

**Comment by retorquere** [comment]
Are #5 and #6 a single issue?

**Comment by retorquere** [comment]
I think you mean itemKey, not itemID. You'd be looking at something like

```
const doi = item.getField('DOI');
const itemRef = doi ? getShortDOI(doi) : item.group + ":" + item.key;
const archiveLocation = item.getField('archiveLocation');
if (archiveLocation !== itemRef) item.setField('archiveLocation', `${itemRef};${archiveLocation}`)
```

But `getShortDOI` actively queries the DOI service. I'd rather rely on detecting that there's a shortdoi already present (meaning: is there an `DOI` field, and does it look like `/^(https?:\/\/)doi\.org/[a-z]+$/`)

item.group is more involved if you want the key as in #2, but I have the code to do it.

What would trigger this behavior?

**Comment by bjohas** [comment]
Sorry, it was libraryID not group. (What is item.group anyway? Sorry for the confusion.)

This would be triggered by new items being added, same as https://github.com/bwiernik/zotero-shortdoi/releases/latest. Maybe it needs to run-time patch that plugin, to always run after it? Alternatively, I guess as that's a plugin, maybe you could do a PR on the plugin, and the plugin checked whether the 'edtechhub' plugin is available, and if so, runs it when it's done?

Here's a slightly different logic (now with libraryID too):

```
const doi = item.getField('DOI');
var itemRef = "";
if (doi) {
  if (doi.match(/^(https?:\/\/)doi\.org/[a-z]+$/) {
    itemRef = doi;
  } else {
    itemRef = getShortDOI(doi);
  }
} else {
  itemRef = item.libraryID + ":" + item.key;
};
const archiveLocation = item.getField('archiveLocation');
if (!archiveLocation.match(itemRef)) item.setField('archiveLocation', `${itemRef};${archiveLocation}`)
```

**Comment by retorquere** [comment]
There's no item.group, but I still think you'd want the library key, not the library id, like in #2.

For a PR to another plugin, you'd have to lobby for it there first. It'd be a shame to do the work and have it rejected, and I can't lobby for it because I'm not the problem owner.

**Comment by bjohas** [comment]
Continuing discussion here. So how do we know that the short-doi plugin has finished? The plugin creates a 'no doi found' tag, so maybe we could look for items that either 

- have a doi  (whcih we can reuse)
- have a "no doi found" tag (where we need to create our own id)
- sometimes the short-doi plugin tags items as "multiple DOI found" - for those we should just create our own id as well.

Does that work?

**Comment by retorquere** [comment]
You can't know the shortdoi plugin specifically has finished, but when it's done it saves the item, and we get notified of that.

Whatever behavior you want should work from the premise "the item has changed for reasons unknown, so now I will..."

If you can describe the desired behavior from the point of view of "item changed, this is what the item looks like now" (which we can know) rather than "this is what just happened to the item" (which we don't), that can probably be done.

**Comment by bjohas** [comment]
Yes, that's possible.

How about this:
```
item has changed
if (item has a DOI OR item.extras matches "DOI:") {
  if (there's isn't a shortDOI) {
    getShortDOI
  }
  prepend shortDOI to item.archiveLocation
} else {
  if (item is tagged with "no doi found") {
    create our own id
    prepend our own id to the item.archiveLocation
  }  else {
     // Do nothing: Either multiple doi or short-doi-extension hasn't run, so we leave it for now.
     // We'll get notified again once short-doi-extension has run or if a DOI has been added.
  }
}
```

I have another thought: From your usage of Zotero, is it wise to use the archiveLocation field? Dealing mostly with journals etc, it's not used widely. However, maybe we are safer just using the extras field? What do you think?

**Comment by retorquere** [comment]
I don't ever use the `archiveLocation` field but that doesn't mean anything; I'm not representative of how people use Zotero at all. I use it as a BibTeX manager, which is about as far as you can get from typical usage as possible.

The `getShortDOI` from above implies I should grab it if not present but I really don't think it's a good idea to duplicate the code from the zotero-shortdoi plugin. It'd be best to either demand it be installed so I can use it's code, or that I simply detect that there's a shortdoi either in the `extra` field or in the `DOI` field.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 0.0.5.16](https://github.com/retorquere/zotero-edtechhub/releases/download/builds/zotero-edtechhub-0.0.5.16.xpi) ("auto-generate ID in archiveLocation")

Install in Zotero by downloading [test build 0.0.5.16](https://github.com/retorquere/zotero-edtechhub/releases/download/builds/zotero-edtechhub-0.0.5.16.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by bjohas** [comment]
Thanks - I couldn't figure out how to trigger thisl It should be on change, right? I tried modifying items / getting long/short DOIs, but archiveLocation wasn't updated.

Yes - we can demand that the zotero-shortdoi extension is installed!

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 0.0.5.17](https://github.com/retorquere/zotero-edtechhub/releases/download/builds/zotero-edtechhub-0.0.5.17.xpi) ("fixes #5")

Install in Zotero by downloading [test build 0.0.5.17](https://github.com/retorquere/zotero-edtechhub/releases/download/builds/zotero-edtechhub-0.0.5.17.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
It didn't do anything yet, I just committed the scaffolding for when we decided on how to proceed. 0.0.5.17 should work.

**Comment by retorquere** [comment]
If you can check whether 0.0.5.17 does what you want I can merge & release.

In general, if @blip-bloop posts a version, that means it's ready for feedback & merge, or I need debug logging -- if @blip-bloop is wrong (doesn't happen often but it does) I'll remove the @blip-bloop comment.

**Comment by bjohas** [comment]
This is very nice - really excited about this - as it will really simplify our work.

(A) I hvae overlooked something. Where items already have a DOI, the zotero-short-doi extension won't make a change, and therefore our extensnion won't process those items. 
(B) Also, our extension would run across all libraries, changing all libraries that I have access to (as short-doi will run on those). However, these have many different purposes, only some of them are EdTech.

Overall, automated triggering is not helpful. It does require user interaction (i.e. an item in the right click menu).

**Comment by retorquere** [comment]
There's no way to use the infrastructure of ShortDOI that does not try to assign the ShortDOI as it goes (and thereby changes the item). I'd strongly suggest to just detect whether there's a shortDOI in the `DOI` or `extra` field and use that if available. The alternative is to replicate part of what ShortDOI does. That seems like a waste (and you'd have to start tracking updates to ShortDOI plugin for maintenance)

**Comment by bjohas** [comment]
OK, that seems fine!

How about we do this:
- If there's a shortdoi in the extras or in the DOI field, let's use it
- if there's a doi in the extras or in the doi field, let's use it (some items don't as yet have doi fields)
- Otherwise assign our own ID as before.

Does that work?

**Comment by retorquere** [comment]
So no more check on "no doi found"?

**Comment by retorquere** [comment]
Or is that what you mean by "as before"?

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 0.0.6.21](https://github.com/retorquere/zotero-edtechhub/releases/download/builds/zotero-edtechhub-0.0.6.21.xpi) ("fixes #5")

Install in Zotero by downloading [test build 0.0.6.21](https://github.com/retorquere/zotero-edtechhub/releases/download/builds/zotero-edtechhub-0.0.6.21.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by bjohas** [comment]
Perfect!

Just to double check, this doesn't do automated assignment, but only triggered through the menu action. That is exactly how it should be: No automated assignment, but only triggered through the menu action.

**Comment by bjohas** [comment]
Just to record it, can you share what strings are searched for in 'extras'?

**Comment by retorquere** [comment]
That is correct, only manual now. It scans for `DOI:` and `shortdoi:` (both case insensitive) at the start of a line in `extra`. Lines in `extra` overrule the `DOI` field if both are present.
