### ISSUE TITLE
Merging: combine 'locInArchive'

### ISSUE THREAD

**Issue by bjohas** [retorquere/zotero-edtechhub#6]
Let's merge the "loc in archive": The "retained item" has
```
retainedItem.locInArchive = retainedItem.locInArchive + ";" + removedItem.locInArchive
```

Reason: We intent to use LocInArchive to assign items plain-text unique ids, that can be used to refer to the item. The process for doing so is described here: https://github.com/edtechhub/zotero-edtechhub/issues/5. The 'merge' needs to be sensitive to this, and retain the locInArchive of both items in the locInArchive field.

**Comment by retorquere** [comment]
There isn't a `locInArchive` field in Zotero. Below is the full list of fields per type, along with their aliases they're also known as.

|type|field|alias|
| --- | --- | --- |
|artwork|abstractNote||
|artwork|accessDate||
|artwork|archive||
|artwork|archiveLocation||
|artwork|artworkSize||
|artwork|callNumber||
|artwork|date||
|artwork|extra||
|artwork|language||
|artwork|libraryCatalog||
|artwork|medium|artworkMedium|
|artwork|rights||
|artwork|shortTitle||
|artwork|title||
|artwork|url||
|attachment|accessDate||
|attachment|title||
|attachment|url||
|audioRecording|ISBN||
|audioRecording|abstractNote||
|audioRecording|accessDate||
|audioRecording|archive||
|audioRecording|archiveLocation||
|audioRecording|callNumber||
|audioRecording|date||
|audioRecording|extra||
|audioRecording|language||
|audioRecording|libraryCatalog||
|audioRecording|medium|audioRecordingFormat|
|audioRecording|numberOfVolumes||
|audioRecording|place||
|audioRecording|publisher|label|
|audioRecording|rights||
|audioRecording|runningTime||
|audioRecording|seriesTitle||
|audioRecording|shortTitle||
|audioRecording|title||
|audioRecording|url||
|audioRecording|volume||
|bill|abstractNote||
|bill|accessDate||
|bill|code||
|bill|date||
|bill|extra||
|bill|history||
|bill|language||
|bill|legislativeBody||
|bill|number|billNumber|
|bill|pages|codePages|
|bill|rights||
|bill|section||
|bill|session||
|bill|shortTitle||
|bill|title||
|bill|url||
|bill|volume|codeVolume|
|blogPost|abstractNote||
|blogPost|accessDate||
|blogPost|date||
|blogPost|extra||
|blogPost|language||
|blogPost|publicationTitle|blogTitle|
|blogPost|rights||
|blogPost|shortTitle||
|blogPost|title||
|blogPost|type|websiteType|
|blogPost|url||
|book|ISBN||
|book|abstractNote||
|book|accessDate||
|book|archive||
|book|archiveLocation||
|book|callNumber||
|book|date||
|book|edition||
|book|extra||
|book|language||
|book|libraryCatalog||
|book|numPages||
|book|numberOfVolumes||
|book|place||
|book|publisher||
|book|rights||
|book|series||
|book|seriesNumber||
|book|shortTitle||
|book|title||
|book|url||
|book|volume||
|bookSection|ISBN||
|bookSection|abstractNote||
|bookSection|accessDate||
|bookSection|archive||
|bookSection|archiveLocation||
|bookSection|callNumber||
|bookSection|date||
|bookSection|edition||
|bookSection|extra||
|bookSection|language||
|bookSection|libraryCatalog||
|bookSection|numberOfVolumes||
|bookSection|pages||
|bookSection|place||
|bookSection|publicationTitle|bookTitle|
|bookSection|publisher||
|bookSection|rights||
|bookSection|series||
|bookSection|seriesNumber||
|bookSection|shortTitle||
|bookSection|title||
|bookSection|url||
|bookSection|volume||
|case|abstractNote||
|case|accessDate||
|case|court||
|case|date|dateDecided|
|case|extra||
|case|history||
|case|language||
|case|number|docketNumber|
|case|pages|firstPage|
|case|reporter||
|case|rights||
|case|shortTitle||
|case|title|caseName|
|case|url||
|case|volume|reporterVolume|
|computerProgram|ISBN||
|computerProgram|abstractNote||
|computerProgram|accessDate||
|computerProgram|archive||
|computerProgram|archiveLocation||
|computerProgram|callNumber||
|computerProgram|date||
|computerProgram|extra||
|computerProgram|libraryCatalog||
|computerProgram|place||
|computerProgram|programmingLanguage||
|computerProgram|publisher|company|
|computerProgram|rights||
|computerProgram|seriesTitle||
|computerProgram|shortTitle||
|computerProgram|system||
|computerProgram|title||
|computerProgram|url||
|computerProgram|versionNumber||
|conferencePaper|DOI||
|conferencePaper|ISBN||
|conferencePaper|abstractNote||
|conferencePaper|accessDate||
|conferencePaper|archive||
|conferencePaper|archiveLocation||
|conferencePaper|callNumber||
|conferencePaper|conferenceName||
|conferencePaper|date||
|conferencePaper|extra||
|conferencePaper|language||
|conferencePaper|libraryCatalog||
|conferencePaper|pages||
|conferencePaper|place||
|conferencePaper|publicationTitle|proceedingsTitle|
|conferencePaper|publisher||
|conferencePaper|rights||
|conferencePaper|series||
|conferencePaper|shortTitle||
|conferencePaper|title||
|conferencePaper|url||
|conferencePaper|volume||
|dictionaryEntry|ISBN||
|dictionaryEntry|abstractNote||
|dictionaryEntry|accessDate||
|dictionaryEntry|archive||
|dictionaryEntry|archiveLocation||
|dictionaryEntry|callNumber||
|dictionaryEntry|date||
|dictionaryEntry|edition||
|dictionaryEntry|extra||
|dictionaryEntry|language||
|dictionaryEntry|libraryCatalog||
|dictionaryEntry|numberOfVolumes||
|dictionaryEntry|pages||
|dictionaryEntry|place||
|dictionaryEntry|publicationTitle|dictionaryTitle|
|dictionaryEntry|publisher||
|dictionaryEntry|rights||
|dictionaryEntry|series||
|dictionaryEntry|seriesNumber||
|dictionaryEntry|shortTitle||
|dictionaryEntry|title||
|dictionaryEntry|url||
|dictionaryEntry|volume||
|document|abstractNote||
|document|accessDate||
|document|archive||
|document|archiveLocation||
|document|callNumber||
|document|date||
|document|extra||
|document|language||
|document|libraryCatalog||
|document|publisher||
|document|rights||
|document|shortTitle||
|document|title||
|document|url||
|email|abstractNote||
|email|accessDate||
|email|date||
|email|extra||
|email|language||
|email|rights||
|email|shortTitle||
|email|title|subject|
|email|url||
|encyclopediaArticle|ISBN||
|encyclopediaArticle|abstractNote||
|encyclopediaArticle|accessDate||
|encyclopediaArticle|archive||
|encyclopediaArticle|archiveLocation||
|encyclopediaArticle|callNumber||
|encyclopediaArticle|date||
|encyclopediaArticle|edition||
|encyclopediaArticle|extra||
|encyclopediaArticle|language||
|encyclopediaArticle|libraryCatalog||
|encyclopediaArticle|numberOfVolumes||
|encyclopediaArticle|pages||
|encyclopediaArticle|place||
|encyclopediaArticle|publicationTitle|encyclopediaTitle|
|encyclopediaArticle|publisher||
|encyclopediaArticle|rights||
|encyclopediaArticle|series||
|encyclopediaArticle|seriesNumber||
|encyclopediaArticle|shortTitle||
|encyclopediaArticle|title||
|encyclopediaArticle|url||
|encyclopediaArticle|volume||
|film|abstractNote||
|film|accessDate||
|film|archive||
|film|archiveLocation||
|film|callNumber||
|film|date||
|film|extra||
|film|language||
|film|libraryCatalog||
|film|medium|videoRecordingFormat|
|film|publisher|distributor|
|film|rights||
|film|runningTime||
|film|shortTitle||
|film|title||
|film|type|genre|
|film|url||
|forumPost|abstractNote||
|forumPost|accessDate||
|forumPost|date||
|forumPost|extra||
|forumPost|language||
|forumPost|publicationTitle|forumTitle|
|forumPost|rights||
|forumPost|shortTitle||
|forumPost|title||
|forumPost|type|postType|
|forumPost|url||
|hearing|abstractNote||
|hearing|accessDate||
|hearing|committee||
|hearing|date||
|hearing|extra||
|hearing|history||
|hearing|language||
|hearing|legislativeBody||
|hearing|number|documentNumber|
|hearing|numberOfVolumes||
|hearing|pages||
|hearing|place||
|hearing|publisher||
|hearing|rights||
|hearing|session||
|hearing|shortTitle||
|hearing|title||
|hearing|url||
|instantMessage|abstractNote||
|instantMessage|accessDate||
|instantMessage|date||
|instantMessage|extra||
|instantMessage|language||
|instantMessage|rights||
|instantMessage|shortTitle||
|instantMessage|title||
|instantMessage|url||
|interview|abstractNote||
|interview|accessDate||
|interview|archive||
|interview|archiveLocation||
|interview|callNumber||
|interview|date||
|interview|extra||
|interview|language||
|interview|libraryCatalog||
|interview|medium|interviewMedium|
|interview|rights||
|interview|shortTitle||
|interview|title||
|interview|url||
|journalArticle|DOI||
|journalArticle|ISSN||
|journalArticle|abstractNote||
|journalArticle|accessDate||
|journalArticle|archive||
|journalArticle|archiveLocation||
|journalArticle|callNumber||
|journalArticle|date||
|journalArticle|extra||
|journalArticle|issue||
|journalArticle|journalAbbreviation||
|journalArticle|language||
|journalArticle|libraryCatalog||
|journalArticle|pages||
|journalArticle|publicationTitle||
|journalArticle|rights||
|journalArticle|series||
|journalArticle|seriesText||
|journalArticle|seriesTitle||
|journalArticle|shortTitle||
|journalArticle|title||
|journalArticle|url||
|journalArticle|volume||
|letter|abstractNote||
|letter|accessDate||
|letter|archive||
|letter|archiveLocation||
|letter|callNumber||
|letter|date||
|letter|extra||
|letter|language||
|letter|libraryCatalog||
|letter|rights||
|letter|shortTitle||
|letter|title||
|letter|type|letterType|
|letter|url||
|magazineArticle|ISSN||
|magazineArticle|abstractNote||
|magazineArticle|accessDate||
|magazineArticle|archive||
|magazineArticle|archiveLocation||
|magazineArticle|callNumber||
|magazineArticle|date||
|magazineArticle|extra||
|magazineArticle|issue||
|magazineArticle|language||
|magazineArticle|libraryCatalog||
|magazineArticle|pages||
|magazineArticle|publicationTitle||
|magazineArticle|rights||
|magazineArticle|shortTitle||
|magazineArticle|title||
|magazineArticle|url||
|magazineArticle|volume||
|manuscript|abstractNote||
|manuscript|accessDate||
|manuscript|archive||
|manuscript|archiveLocation||
|manuscript|callNumber||
|manuscript|date||
|manuscript|extra||
|manuscript|language||
|manuscript|libraryCatalog||
|manuscript|numPages||
|manuscript|place||
|manuscript|rights||
|manuscript|shortTitle||
|manuscript|title||
|manuscript|type|manuscriptType|
|manuscript|url||
|map|ISBN||
|map|abstractNote||
|map|accessDate||
|map|archive||
|map|archiveLocation||
|map|callNumber||
|map|date||
|map|edition||
|map|extra||
|map|language||
|map|libraryCatalog||
|map|place||
|map|publisher||
|map|rights||
|map|scale||
|map|seriesTitle||
|map|shortTitle||
|map|title||
|map|type|mapType|
|map|url||
|newspaperArticle|ISSN||
|newspaperArticle|abstractNote||
|newspaperArticle|accessDate||
|newspaperArticle|archive||
|newspaperArticle|archiveLocation||
|newspaperArticle|callNumber||
|newspaperArticle|date||
|newspaperArticle|edition||
|newspaperArticle|extra||
|newspaperArticle|language||
|newspaperArticle|libraryCatalog||
|newspaperArticle|pages||
|newspaperArticle|place||
|newspaperArticle|publicationTitle||
|newspaperArticle|rights||
|newspaperArticle|section||
|newspaperArticle|shortTitle||
|newspaperArticle|title||
|newspaperArticle|url||
|patent|abstractNote||
|patent|accessDate||
|patent|applicationNumber||
|patent|assignee||
|patent|country||
|patent|date|issueDate|
|patent|extra||
|patent|filingDate||
|patent|issuingAuthority||
|patent|language||
|patent|legalStatus||
|patent|number|patentNumber|
|patent|pages||
|patent|place||
|patent|priorityNumbers||
|patent|references||
|patent|rights||
|patent|shortTitle||
|patent|title||
|patent|url||
|podcast|abstractNote||
|podcast|accessDate||
|podcast|extra||
|podcast|language||
|podcast|medium|audioFileType|
|podcast|number|episodeNumber|
|podcast|rights||
|podcast|runningTime||
|podcast|seriesTitle||
|podcast|shortTitle||
|podcast|title||
|podcast|url||
|presentation|abstractNote||
|presentation|accessDate||
|presentation|date||
|presentation|extra||
|presentation|language||
|presentation|meetingName||
|presentation|place||
|presentation|rights||
|presentation|shortTitle||
|presentation|title||
|presentation|type|presentationType|
|presentation|url||
|radioBroadcast|abstractNote||
|radioBroadcast|accessDate||
|radioBroadcast|archive||
|radioBroadcast|archiveLocation||
|radioBroadcast|callNumber||
|radioBroadcast|date||
|radioBroadcast|extra||
|radioBroadcast|language||
|radioBroadcast|libraryCatalog||
|radioBroadcast|medium|audioRecordingFormat|
|radioBroadcast|number|episodeNumber|
|radioBroadcast|place||
|radioBroadcast|publicationTitle|programTitle|
|radioBroadcast|publisher|network|
|radioBroadcast|rights||
|radioBroadcast|runningTime||
|radioBroadcast|shortTitle||
|radioBroadcast|title||
|radioBroadcast|url||
|report|abstractNote||
|report|accessDate||
|report|archive||
|report|archiveLocation||
|report|callNumber||
|report|date||
|report|extra||
|report|language||
|report|libraryCatalog||
|report|number|reportNumber|
|report|pages||
|report|place||
|report|publisher|institution|
|report|rights||
|report|seriesTitle||
|report|shortTitle||
|report|title||
|report|type|reportType|
|report|url||
|statute|abstractNote||
|statute|accessDate||
|statute|code||
|statute|codeNumber||
|statute|date|dateEnacted|
|statute|extra||
|statute|history||
|statute|language||
|statute|number|publicLawNumber|
|statute|pages||
|statute|rights||
|statute|section||
|statute|session||
|statute|shortTitle||
|statute|title|nameOfAct|
|statute|url||
|thesis|abstractNote||
|thesis|accessDate||
|thesis|archive||
|thesis|archiveLocation||
|thesis|callNumber||
|thesis|date||
|thesis|extra||
|thesis|language||
|thesis|libraryCatalog||
|thesis|numPages||
|thesis|place||
|thesis|publisher|university|
|thesis|rights||
|thesis|shortTitle||
|thesis|title||
|thesis|type|thesisType|
|thesis|url||
|tvBroadcast|abstractNote||
|tvBroadcast|accessDate||
|tvBroadcast|archive||
|tvBroadcast|archiveLocation||
|tvBroadcast|callNumber||
|tvBroadcast|date||
|tvBroadcast|extra||
|tvBroadcast|language||
|tvBroadcast|libraryCatalog||
|tvBroadcast|medium|videoRecordingFormat|
|tvBroadcast|number|episodeNumber|
|tvBroadcast|place||
|tvBroadcast|publicationTitle|programTitle|
|tvBroadcast|publisher|network|
|tvBroadcast|rights||
|tvBroadcast|runningTime||
|tvBroadcast|shortTitle||
|tvBroadcast|title||
|tvBroadcast|url||
|videoRecording|ISBN||
|videoRecording|abstractNote||
|videoRecording|accessDate||
|videoRecording|archive||
|videoRecording|archiveLocation||
|videoRecording|callNumber||
|videoRecording|date||
|videoRecording|extra||
|videoRecording|language||
|videoRecording|libraryCatalog||
|videoRecording|medium|videoRecordingFormat|
|videoRecording|numberOfVolumes||
|videoRecording|place||
|videoRecording|publisher|studio|
|videoRecording|rights||
|videoRecording|runningTime||
|videoRecording|seriesTitle||
|videoRecording|shortTitle||
|videoRecording|title||
|videoRecording|url||
|videoRecording|volume||
|webpage|abstractNote||
|webpage|accessDate||
|webpage|date||
|webpage|extra||
|webpage|language||
|webpage|publicationTitle|websiteTitle|
|webpage|rights||
|webpage|shortTitle||
|webpage|title||
|webpage|type|websiteType|
|webpage|url||

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 0.0.4.12](https://github.com/retorquere/zotero-edtechhub/releases/download/builds/zotero-edtechhub-0.0.4.12.xpi) ("collect archiveLocation")

Install in Zotero by downloading [test build 0.0.4.12](https://github.com/retorquere/zotero-edtechhub/releases/download/builds/zotero-edtechhub-0.0.4.12.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by bjohas** [comment]
It's archiveLocation. In the ui it's called "loc. In archive"

**Comment by retorquere** [comment]
That's what I figured, try the build above

**Comment by bjohas** [comment]
Perfect, thank you!

(The plugin doesn't combing the locInArchive if it's the same on both items - exactly as needed, thank you!)

This can be closed!

**Comment by retorquere** [comment]
I've made you a contributor which means you can label, but also close issues, but please don't close issues. I keep them open so I know to merge changes to master. Versions posted on issues do not yet have the functionality merged to master.

**Comment by bjohas** [comment]
Ah ok - thank you. I'll just label!
