### ISSUE TITLE
Can this plugin install other plugins and/or configure Zotero

### ISSUE THREAD

**Issue by bjohas** [retorquere/zotero-edtechhub#8]
When this plugin is installed, could it ensure that ZotFile, Zutilo and short-doi are installed? Could it also install a few preferences (e.g. for ZotFile and Zutilo, and some translators)? I assume at least the second one is possible?

Ratoinale: This would accellerate setting up Zotero for our users.

**Comment by retorquere** [comment]
It can verify whether they are installed, but it cannot install them.

It could do the settings but we should be very careful around this. There's not really a way to check whether the user changed the prefs or whether we did, so this plugin would always revert any changes made by users.

We can display a warning on start when plugins are missing, or when prefs are not what we would expect them to be, but I'm not too keen on always reversing user intent.

**Comment by bjohas** [comment]
OK, a warning would be good, especially for short-doi, as we're building on that. The following warnings should occur: 
- short-dois. "The short-doi plugin is not available, please install it from here. [link]." 
- Zutilo: "The use of the Zutilo plugin is recommended. Please install it from here [link]." 
- ZotFile: "The use of the ZotFile plugin is recommended. Please install it from here [link]." 
The warnings should occur at every application launch, but maybe with a 'do not show again' button. 

Regarding the settings: They would normally be empty. How about this:

- Application launched
- ZotFile settings are empty (I'll post the list.)
- Our plugin warns once: "Your ZotFile settings are empty. Would you like to install the EdTech Hub settings?"
- If yes, edtechhub settings are installed.

Is it also possible to check for some translators / install them?

Alternatively, all of this could be through a button in the prefs for our plugin, but that means UI....

Overall, this is NOT high priority. We could do some trialling with users instead, and just give clear instructions, to see how that goes - so let's shelve this until later.

**Comment by retorquere** [comment]
I'll leave the trialing with users to you -- you can have users have the discussion here, but I'll wait for you to make a decision. I can't have multiple deciders on a given issue.

**Comment by bjohas** [comment]
Yes, absolutely! Let's pause this issue for 2-3 weeks while I gather further info from our users. Thanks!!

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 0.0.5.18](https://github.com/retorquere/zotero-edtechhub/releases/download/builds/zotero-edtechhub-0.0.5.18.xpi) ("show missing plugins")

Install in Zotero by downloading [test build 0.0.5.18](https://github.com/retorquere/zotero-edtechhub/releases/download/builds/zotero-edtechhub-0.0.5.18.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
You're stacking multiple issues. Yes, translators can be installed, but that's a different thing. It makes it harder to finish up issues if we get stuck in a phase of this-part-but-not-that when the parts could be separate.

**Comment by bjohas** [comment]
OK, thanks - yes, that's fair. I am happy with the notifications that the plugin does as in 0.0.5.18. So let's tick that off. Let\s leave the translators and installation of settings for now - I'll do some user testing on that, and then report back!

Thanks for getting the notifications going, that's really helpful!
